# Generated by Django 6.0.6 on 2026-06-09 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(choices=[('consulta', 'Consulta general'), ('empresa', 'Quiero publicar una oferta'), ('problema', 'Reportar un problema'), ('sugerencia', 'Sugerencia de mejora')], default='consulta', max_length=20)),
                ('mensaje', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='contacto/')),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('requisitos', models.TextField()),
                ('habilidades_requeridas', models.TextField(blank=True)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=20)),
                ('salario_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salario_max', models.PositiveIntegerField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('publicada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('resumen', models.TextField(blank=True)),
                ('habilidades', models.TextField(blank=True)),
                ('cargo_actual', models.CharField(blank=True, max_length=200)),
                ('annos_experiencia', models.PositiveIntegerField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carta_presentacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('en_revision', 'En revisión'), ('entrevista', 'Entrevista agendada'), ('rechazada', 'Rechazada'), ('seleccionada', 'Seleccionada')], default='enviada', max_length=20)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='portal.ofertalaboral')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'oferta')},
            },
        ),
    ]
